# Generated by Django 3.2.4 on 2021-06-11 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdns', '0003_domain_domparent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='owner',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
