# Generated by Django 3.2.4 on 2021-06-11 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdns', '0004_alter_domain_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resp',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
