# Generated by Django 3.2.9 on 2021-11-10 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sdns', '0005_alter_resp_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='domain',
            options={'managed': True, 'verbose_name': 'Nome do model', 'verbose_name_plural': 'Nome no plural'},
        ),
        migrations.AlterModelTable(
            name='domain',
            table='nome da tabela',
        ),
    ]
