# Generated by Django 3.2.9 on 2021-11-10 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sdns', '0006_auto_20211110_1753'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='domain',
            options={'managed': True, 'verbose_name': 'Registro', 'verbose_name_plural': 'Registros'},
        ),
    ]
