# Generated by Django 3.2.9 on 2021-11-10 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdns', '0008_auto_20211110_1815'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cts',
            constraint=models.UniqueConstraint(fields=('registro', 'reg', 'content'), name='unique_Cts'),
        ),
    ]
