# Generated by Django 3.2.9 on 2021-11-11 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sdns', '0009_cts_unique_cts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='domain',
            options={'managed': True, 'verbose_name': 'Dominio', 'verbose_name_plural': 'Dominios - Realms'},
        ),
    ]
